version: "3.8"

networks:
  proxy_bridge:
    external: true

services:
  contentful-app:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    container_name: contentful-app-container
    restart: always
    networks:
      proxy_bridge:
    env_file:
      - ./env/server.env
    labels:
      traefik.enable: true
      traefik.http.routers.contentful-app-secure.entrypoints: websecure
      traefik.http.routers.contentful-app-secure.rule: Host(`cedricpaje.fr`) || Host(`www.cedricpaje.fr`)
      traefik.http.services.contentful-app-secure.loadbalancer.server.port: 80
      traefik.http.routers.contentful-app-secure.middlewares: main-redirect@file
      traefik.docker.network: proxy_bridge
